[workspace]
members = [
  # # Clickhouse
  # "clickhouse-evm-transfers",
  # "clickhouse-evm-dex",

  # Tokens
  "transfers",

  # DEX
  "dex/sunswap",
  "dex/justswap",
  "dex/sunpump",
  "dex/uniswap-v2",
  "dex/uniswap-v3",
  "dex/uniswap-v4",

  # Common
  "proto",
  "common",
]
resolver = "2"

[workspace.package]
description = "EVM Substreams modules"
edition = "2021"
version = "0.0.0"
license = "Apache-2.0"

[workspace.dependencies]
substreams = "0.7.0"
substreams-abis = "0.7.1"
substreams-ethereum = "0.11.1"
substreams-database-change = "3.0.0"
prost = "0.13"
prost-types = "0.13"

[profile.release]
lto = true
